mainfu/mytitle/mytitle/urls.py
from django.contrib import admin
from django.urls import path
from Diy import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', views.reg, name='reg'),
    path('login/', views.logIn, name='login'),
    path('get_valid_img/', views.get_valid_img),
    path('index/', views.index),
]

mainfu/mytitle/Diy/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class UserInfo(AbstractUser):
    nid = models.AutoField(primary_key=True)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    telephone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to = 'avatars/',default="/avatars/default.png")
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    def __str__(self):
        return self.username

mainfu/mytitle/Diy/forms.py
from django import forms
from django.forms import widgets
from django.core.exceptions import NON_FIELD_ERRORS,ValidationError
from .models import *


class RegisterForm(forms.Form):
    user = forms.CharField(min_length=5,
                           help_text="6~16个字符，区分大小写",
                           error_messages={"required":"用户名不能为空",
                                           "min_length": "最小长度为5",
                                        },
                           widget=widgets.TextInput(attrs={"class":"form-control","placeholder":"用户名"}))

    pwd = forms.CharField(min_length=5,
                           help_text="6~16个字符，区分大小写",
                           error_messages={"required": "不能为空",
                                           "min_length": "最小长度为5",
                                           },
                          widget=widgets.PasswordInput(attrs={"class":"form-control","placeholder":"密码"}))

    repeat_pwd = forms.CharField(min_length=5,

                           error_messages={"required": "不能为空",
                                            },
                                 widget=widgets.PasswordInput(attrs={"class":"form-control","placeholder":"确认密码"}))

    email = forms.CharField(
                                 error_messages={"required": "不能为空",
                                                 "invalid":"格式错误"
                                                 },
                                widget=widgets.EmailInput(attrs={"class":"form-control","placeholder":"邮箱"}))


    def clean_user(self):
        val = self.cleaned_data.get("user")
        user =  UserInfo.objects.filter(username=val)
        if not user:
            return val
        else:
            raise ValidationError("用户已存在!")


    def clean(self):
        pwd = self.cleaned_data.get("pwd")
        repeat_pwd = self.cleaned_data.get("repeat_pwd")
        if pwd and repeat_pwd:
            if pwd == repeat_pwd:
                return self.cleaned_data
            else:
                raise ValidationError("两次密码不一致！")
        else:
            return self.cleaned_data

mainfu/mytitle/Diy/views.py
from django.shortcuts import render,redirect,HttpResponse
from .models import *
from Diy.forms import *
from django.contrib import auth

# Create your views here.

#注册页面

def reg(request):
    avatar_obj = request.FILES.get("avatars")
    # print(type(avatar_obj))
    if request.is_ajax():
        register_form = RegisterForm(request.POST)
        reg_response = {"user":None,"error_msg":None}
        if register_form.is_valid():
            user = register_form.cleaned_data.get("user")
            pwd = register_form.cleaned_data.get("pwd")
            email = register_form.cleaned_data.get("email")
            avatar_obj = request.FILES.get("avatars")
            user_obj = UserInfo.objects.create_user(username=user,password=pwd,email=email,avatar=avatar_obj)
            reg_response["user"] = user_obj.username
        else:
             reg_response["error_msg"] = register_form.errors
        import json
        return HttpResponse(json.dumps(reg_response))
    register_form=RegisterForm()
    return render(request,'register.html',locals())

#登录页面
def logIn(request):
    if request.is_ajax():
        print(request.POST)
        user=request.POST.get("user")
        pwd=request.POST.get("pwd")
        valid_code=request.POST.get("valid_code")
        code_str=request.session.get("random_code_str")
        print("random_code_str",code_str)
        login_response={"user":None,"error_msg":""}
        if valid_code.upper()==code_str.upper():
            user=auth.authenticate(username=user,password=pwd)
            if user:
                login_response["user"]=user.username
                auth.login(request,user)
                print("===",request.session.get("random_code_str"))
            else:
                login_response["error_msg"] ="username or password error!"
        else:
            login_response["error_msg"]="valid code error!"
        import json
        return HttpResponse(json.dumps(login_response))

    return render(request,'login.html')

#验证码
def get_valid_img(request):
    import random
    def get_random_color():
        return (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
    from PIL import Image
    from io import BytesIO
    from PIL import ImageDraw, ImageFont
    f = BytesIO()
    image = Image.new(mode="RGB", size=(120, 80), color=get_random_color())
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype("Diy/static/fonts/kumo.ttf", size=36)

    temp = []
    for i in range(5):
        random_char = random.choice(
            [str(random.randint(0, 9)), chr(random.randint(65, 90)), chr(random.randint(97, 122))])
        draw.text((i * 24, 26), random_char, get_random_color(), font=font)
        temp.append(random_char)
    width = 120
    height = 80
    image.save(f, "png")
    data = f.getvalue()
    request.session["random_code_str"]="".join(temp)
    return HttpResponse(data)

def index(request):

    return render(request,"index.html",locals())

mainfu/mytitle/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
    <link rel="icon" href="/static/img/favicon.ico">
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/index.css">
    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/index.js"></script>
</head>
<body>
<div class="banner" id="nav">
    <div class="colud">
    </div>
    <ul>
        <li><a href="#">新闻模块</a></li>
        <li><a href="#">游戏模块</a></li>
        <li id="list3"><a href="#">购物模块</a></li>
        <li><a href="#">美图模块</a></li>
        <li><a href="#">学习模块</a></li>
        <li><a href="#">视频模块</a></li>
        <li><a href="#">出行模块</a></li>
        <li><a href="#">关于我们</a></li>
    </ul>
</div>

<div class="fdj" id="box">
        <div class="small">
            <img src="/static/img/001.jpg" alt=""/>
            <div class="mask"></div>
        </div>
        <div class="big">
            <img src="/static/img/0001.jpg" alt=""/>
        </div>
    </div>
</body>
</html>

<script>
    window.onload=function(){
        var nav =document.getElementById("nav");
        var colud =nav.children[0];
        var lis=nav.children[1].children;
        var current=0;
        for(var i=0; i<lis.length; i++)
        {
            lis[i].onmouseover=function(){
                target=this.offsetLeft;
            }
            lis[i].onmouseout=function(){
                target=current;

            }
            lis[i].onclick=function(){
                current=this.offsetLeft;
            }
        }
        var target= 0, leader=0;
        setInterval(function(){
            leader=leader+(target-leader)/10;
            colud.style.left=leader+"px";
        },10)


            var box=document.getElementById("box");
            var small=box.children[0];
            var big = box.children[1];
            var mask =small.children[1];
            var bigImages =big.children[0];
            small.onmouseover=function(){
                mask.style.display="block";
                big.style.display="block";
            }
            small.onmouseout=function(){
                mask.style.display="none";
                big.style.display="none";
            }
            var x = 0;
            var y = 0;
            small.onmousemove = function(event) {
                var event = event || window.event;
                x=event.clientX-this.offsetParent.offsetLeft-mask.offsetWidth/2;
                y=event.clientY-this.offsetParent.offsetTop-mask.offsetHeight/2;
                if(x<0){
                    x=0;
                }
                else if (x>small.offsetWidth-mask.offsetWidth){
                    x=small.offsetWidth-mask.offsetWidth;
                }
                if(y<0){
                    y=0;
                }
                else if (y>small.offsetHeight-mask.offsetHeight){
                    y=small.offsetHeight-mask.offsetHeight;
                }
                mask.style.left=x+"px";
                mask.style.top=y+"px";
                bigImages.style.left=-x*big.offsetWidth/small.offsetWidth+"px";
                bigImages.style.top=-y*big.offsetHeight/small.offsetHeight+"px";
            }

    }
</script>

mainfu/mytitle/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="icon" href="/static/img/favicon.ico">
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/login.css">
    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/login.js"></script>
</head>
<body>
<h1 id="h1" style="display: block">去领略星辰大海</h1>
<div class="row col-md-offset-5">
    <h1 class="tip" style="color: #2aabd2">未来是你的</h1>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form>
                {% csrf_token %}
                <div class="form-group">
                    <label for="user">用户名</label>
                    <input type="text" class="form-control" id="user" placeholder="用户名">
                </div>
                 <div class="form-group">
                    <label for="pwd">密码</label>
                    <input type="password" class="form-control" id="pwd" placeholder="密码">
                </div>
                <div class="row">
                    <div class="col-md-6">
                         <div class="form-group">
                            <label for="valid_code">验证码</label>
                            <input type="text" class="form-control" id="valid_code" placeholder="验证码">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img id="valid_img" width="260" height="60" src="/get_valid_img/" alt="">
                    </div>
                </div>
                <span class="btn register"><a href="#">注册>></a></span>
                <input type="button" value="登录" class="btn btn-primary pull-right login_btn"> <span class="error"></span>
            </form>
        </div>
    </div>
</div>

</body>
</html>

mainfu/mytitle/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="icon" href="/static/img/favicon.ico">
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/register.css">
    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/register.js"></script>
</head>
<body>
<div class="head clearfix">
    <div class="row header">
        <h3 class="col-md-2">新用户注册</h3>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-5 col-md-offset-3">
            <div class="form-group col-md-offset-5">
                <img src="/static/img/baidu.gif" alt="">
            </div>
            <form class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_user" class="col-sm-3 control-label">用户名：</label>
                    <div class="col-sm-8">
                            {{ register_form.user }}
                            <span class="pull-right error"></span>
                    </div>
                    <span class="pull-right"></span>
                </div>
                <div class="form-group">
                    <label for="id_pwd" class="col-sm-3 control-label">密码：</label>
                    <div class="col-sm-8">
                            {{ register_form.pwd }}
                        <span class="pull-right error"></span>
                    </div>

                </div>
                <div class="form-group">
                    <label for="id_repeat_pwd" class="col-sm-3 control-label">确认密码：</label>
                    <div class="col-sm-8">
                        {{ register_form.repeat_pwd}}
                        <span class="pull-right error"></span>
                    </div>

                </div>
                <div class="form-group">
                    <label for="id_email" class="col-sm-3 control-label">邮箱：</label>
                    <div class="col-sm-8">
                        {{ register_form.email}}
                        <span class="pull-right error"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="avatar" class="col-sm-3 control-label for-avatar">
                        头像:&nbsp;&nbsp;
                        <img class="avatar-img" id="avatar_img" width="60" height="60" src="/static/img/default.png" alt="">
                    </label>
                    <input type="file" id="avatar" style="display: none">
                </div>
                <div class="form-group div-reg">
                    <div class="reg">
                        <button type="button" class="btn btn-primary pull-right reg_btn" style="margin-right:50px">注册</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>